# Generated by Django 5.2.1 on 2025-05-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="signature",
            field=models.CharField(default="Neil", max_length=140),
        ),
    ]
