# Generated by Django 5.2.1 on 2025-06-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("performance_time_start", models.TimeField(verbose_name="Start Time")),
                ("performance_time_end", models.TimeField(verbose_name="End Time")),
                ("venue", models.CharField(max_length=100)),
                ("performer", models.CharField(max_length=100)),
                (
                    "sound_engineer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
