# Generated by Django 5.2.1 on 2025-06-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Your email address"
                    ),
                ),
                ("message", models.TextField(verbose_name="Your message")),
                ("is_read", models.BooleanField(default=False)),
                ("replied_to", models.BooleanField(default=False)),
            ],
        ),
    ]
