# Generated by Django 5.2.1 on 2025-06-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
